# Generated by Django 4.2.1 on 2023-05-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('web_link', models.CharField(max_length=250)),
                ('logo', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('station', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('photo', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=250)),
                ('driver', models.CharField(max_length=250)),
                ('num_of_seats', models.IntegerField()),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_of_company', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_of_buses', to='api.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Adminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('photo', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
