# Generated by Django 4.2.1 on 2023-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
