# Generated by Django 4.2.1 on 2023-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_availablebus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstration',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='availablebus',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
