# Generated by Django 4.2.1 on 2023-05-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_adminstration_photo_alter_availablebus_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_worker', to='api.company'),
            preserve_default=False,
        ),
    ]
