# Generated by Django 4.2.1 on 2023-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='availaible',
            field=models.BooleanField(default=False),
        ),
    ]
