# Generated by Django 4.2.1 on 2023-05-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bus_availaible'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebus',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='added_bus', to='api.worker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availablebus',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_buses', to='api.bus'),
        ),
    ]
