# Generated by Django 4.2.1 on 2023-05-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bus_listed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='availaible',
            new_name='is_availaible',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='listed',
            new_name='is_listed',
        ),
    ]
