# Generated by Django 4.2.1 on 2023-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_availaible_bus_is_availaible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='is_availaible',
            field=models.BooleanField(default=True),
        ),
    ]
