# Generated by Django 4.2.1 on 2023-06-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.seat'),
            preserve_default=False,
        ),
    ]
