# Generated by Django 4.2.1 on 2023-06-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_bus_seat_bus_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.bus'),
            preserve_default=False,
        ),
    ]
