# Generated by Django 4.2.1 on 2023-06-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_bus_seat_seat_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebus',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.customer'),
            preserve_default=False,
        ),
    ]
