# Generated by Django 4.2.1 on 2023-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_availablebus_price_seat_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='station',
            field=models.CharField(default='kality', max_length=250),
            preserve_default=False,
        ),
    ]
